---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hub-apiportal-ui
  namespace: portal-ui
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hub-apiportal-ui
