---
apiVersion: v1
kind: Service
metadata:
  name: hub-apiportal-ui
  namespace: portal-ui
  labels:
    app.kubernetes.io/component: api-portal-ui
    app.kubernetes.io/name: hub-apiportal-ui
spec:
  ports:
  - name: web
    port: 80
    targetPort: 3000
  selector:
    app: hub-apiportal-ui
  type: ClusterIP
