---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customer-api
  namespace: apps
  labels:
    area: customers
    module: crm
spec:
  pathPrefix: "/customers"
  openApiSpec:
    path: /openapi.yaml
    backend:
      service:
        name: customer-app
        port:
          number: 3000
    operationSets:
      - name: customers-operations # The name that will be used when referenced
        matchers:
          - pathPrefix: /customers