apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-ingress
  namespace: apps
  annotations:
    hub.traefik.io/api: customer-api
spec:
  routes:
    - match: Host(`api.docker.localhost`) && PathPrefix(`/world-time-api`)
      kind: Rule
      services:
        - name: world-time-api
          port: 443
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: world-time-api-external-name
  namespace: apps
  labels:
    area: external
    external: name
spec:
  openApiSpec:
    url: https://worldtimeapi.org/api

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: customers-ingress
  namespace: apps
  annotations:
    hub.traefik.io/api: customer-api
spec:
  routes:
    - match: Host(`api.docker.localhost`) && PathPrefix(`/httpbin`)
      kind: Rule
      services:
        - name: httpbin
          port: 443
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: httpbin-external-name
  namespace: apps
  labels:
    area: external
    external: name
spec:
  openApiSpec:
    url: https://httpbin.org/spec.json