---
apiVersion: traefik.io/v1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.docker.localhost`)
      services:
        - name: grafana
          port: 3000
          namespace: monitoring
